name: chatting_app_firebase
description: A modern Flutter chat application using Firebase.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #firebase dependencies
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_messaging: any
  http: any
  intl: any
  shared_preferences: any
  flutter_local_notifications: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
